export const VNODE_SYMBOL = Symbol('spark.vnode')
export const VNODE_FRAGMENT_SYMBOL = Symbol('spark.vnode.fragment')
export const VNODE_HEAD_SYMBOL = Symbol('spark.vnode.head')
export const VNODE_HTML_TAG = Symbol('spark.vnode.html')
export const VNODE_CONTEXT_SYMBOL = Symbol('spark.vnode.context')
